name: Build and Install Package from PKGBUILD

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger builds on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Arch Linux Docker container
      run: |
        docker pull archlinux:latest
        docker run -d --name arch-builder -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest tail -f /dev/null

    - name: Install dependencies for building on Arch Linux
      run: |
        docker exec arch-builder bash -c "pacman -Sy --noconfirm base-devel git"

    - name: Build the package using PKGBUILD
      run: |
        docker exec arch-builder bash -c "cd /workspace && makepkg -si --noconfirm"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: built-package
        path: ./*.pkg.tar.*  # Uploads any package file with possible extensions (zst, xz, gz)
    
    - name: Cleanup
      run: docker rm -f arch-builder
